# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    ## v2 beta1 webinar
    # Source: https://github.com/ezsystems/ezplatform-ui-2.0-introduction

    # Step 1: Add Menu items, using KnpMenuBundle
    # Besides the example php code in src/, further reading on:
    #   Event listeners in Symfony: https://symfony.com/doc/3.4/event_dispatcher.html
    #   Menues with KnpMenu Bundle: http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_service.html

    AppBundle\EventListener\MyAdminUIMenuListener:
        public: true
        tags:
            - { name: kernel.event_subscriber }



    # Step 2: Add Tabs to dashboard, using Pagerfanta
    # Besides the example php code in src/, further reading on:
    #   Pagerfanta Bundle: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle#rendering-pagerfantas
    #   Other examples in Admin UI: https://github.com/ezsystems/ezplatform-admin-ui/tree/master/src/lib/Tab
    #                              (see sub folders)

    AppBundle\Tab\Dashboard\Everyone\EveryoneUserTab:
        parent: EzSystems\EzPlatformAdminUi\Tab\AbstractTab
        public: false
        tags:
            - { name: ezplatform.tab, group: dashboard-everyone }
            #- { name: ezplatform.tab, group: dashboard-my }
            #- { name: ezplatform.tab, group: location-view }

    # Step 3: Add Field editing, using Symfony Forms
    # Besides the example here, further reading on:
    #   Symfony Forms: https://symfony.com/doc/3.4/forms.html


    # Example from 2.0 here for now:
    #
    # Config:
    # EzSystems\RepositoryForms\FieldType\Mapper\CheckboxFormMapper:
    #   tags:
    #     - { name: ez.fieldFormMapper.definition, fieldType: ezboolean }
    #     - { name: ez.fieldFormMapper.value, fieldType: ezboolean }
    #
    # PHP Form handling:
    #   https://github.com/ezsystems/repository-forms/blob/master/lib/FieldType/Mapper/CheckboxFormMapper.php
    #
    # Twig theming for admin ui:
    #   https://github.com/ezsystems/ezplatform-admin-ui/blob/master/src/bundle/Resources/views/fieldtypes/ezboolean.html.twig
