# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    ## v2 beta1 webinar
    # Source: https://github.com/ezsystems/ezplatform-ui-2.0-introduction
    #
    # Step 1: Add Menu items, using KnpMenuBundle

    AppBundle\EventListener\:
        resource: '../../src/AppBundle/EventListener/*'
        public: true
        tags:
            - { name: kernel.event_subscriber }



    # Step 2: Add Tabs to dashboard, using Pagerfanta

    AppBundle\Tab\Dashboard\Everyone\EveryoneUserTab:
        parent: EzSystems\EzPlatformAdminUi\Tab\AbstractTab
        public: false
        tags:
            - { name: ezplatform.tab, group: dashboard-everyone }
            #- { name: ezplatform.tab, group: dashboard-my }
            #- { name: ezplatform.tab, group: location-view }

    # Step 3: Add Field editing, using Symfony Forms

    # Example from 2.0 here for now:
    #
    # Config:
    # EzSystems\RepositoryForms\FieldType\Mapper\CheckboxFormMapper:
    #   tags:
    #     - { name: ez.fieldFormMapper.definition, fieldType: ezboolean }
    #     - { name: ez.fieldFormMapper.value, fieldType: ezboolean }
    #
    # PHP Form handling:
    #   https://github.com/ezsystems/repository-forms/blob/master/lib/FieldType/Mapper/CheckboxFormMapper.php
    #
    # Twig theming for admin ui:
    #   https://github.com/ezsystems/ezplatform-admin-ui/blob/master/src/bundle/Resources/views/fieldtypes/ezboolean.html.twig
