# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    ## v2 beta1 webinar
    #
    # Step 1: Add Menu items

    AppBundle\EventListener\:
        resource: '../../src/AppBundle/EventListener/*'
        public: true
        tags:
            - { name: kernel.event_subscriber }
